name: Static Code Tests

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  static-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init
        working-directory: ./infra

      - name: Terraform validate
        run: terraform validate
        working-directory: ./infra
